import { countries } from "$lib/constants/countries"

export interface Flag {
	name: string,
	icon: string,
	letter?: string,
	morse?: string,
	description?: string
}

export interface FlagCategory {
	header: string,
	isNavigational: boolean,
	flags: Flag[]
}

export const allFlags: FlagCategory[] = [
	{
		header: 'General flags',
		isNavigational: true,
		flags: [
			{letter: 'A', morse: '·-', name: 'Alpfa', icon: 'A', description: 'I have a diver down; keep well clear at slow speed.'},
			{letter: 'B', morse: '-···', name: 'Bravo', icon: 'B', description: 'I am taking in or discharging or carrying dangerous goods.'},
			{letter: 'C', morse: '-·-·', name: 'Charlie', icon: 'C', description: 'Affirmative.'},
			{letter: 'D', morse: '-··', name: 'Delta', icon: 'D', description: 'Keep clear of me; I am maneuvering with difficulty.'},
			{letter: 'E', morse: '·', name: 'Echo', icon: 'E', description: 'I am altering my course to starboard.'},
			{letter: 'F', morse: '··-·', name: 'Foxtrot', icon: 'F', description: 'I am disabled; communicate with me.'},
			{letter: 'G', morse: '--·', name: 'Golf', icon: 'G', description: 'I require a pilot or I am hauling nets (by fishing boats)'},
			{letter: 'H', morse: '····', name: 'Hotel', icon: 'H', description: 'I have a pilot on board.'},
			{letter: 'I', morse: '··', name: 'India', icon: 'I', description: 'I am altering my course to port.'},
			{letter: 'J', morse: '·---', name: 'Juliet', icon: 'J', description: 'I am on fire and have dangerous cargo on board: keep well clear of me. Or I am leaking dangerous cargo.'},
			{letter: 'K', morse: '-·-', name: 'Kilo', icon: 'K', description: 'I wish to communicate with you.'},
			{letter: 'L', morse: '·-··', name: 'Lima', icon: 'L', description: 'Stop immediately.'},
			{letter: 'M', morse: '--', name: 'Mike', icon: 'M', description: 'My vessel is stopped and making no way through the water.'},
			{letter: 'N', morse: '-·', name: 'November', icon: 'N', description: 'Negative.'},
			{letter: 'O', morse: '---', name: 'Oscar', icon: 'O', description: 'Man overboard.'},
			{letter: 'P', morse: '·--·', name: 'Papa', icon: 'P', description: ''},
			{letter: 'Q', morse: '--·-', name: 'Quebec', icon: 'Q', description: 'My vessel is healthy and I request free pratique.'},
			{letter: 'R', morse: '·-·', name: 'Romeo', icon: 'R', description: 'No ICS meaning as single flag. Prior to 1969: The way is off my ship; you may feel your way past me.'},
			{letter: 'S', morse: '···', name: 'Sierra', icon: 'S', description: 'I am operating astern propulsion.'},
			{letter: 'T', morse: '-', name: 'Tango', icon: 'T', description: 'Keep clear of me. Fishing boats: "Keep clear of me; I am engaged in pair trawling."'},
			{letter: 'U', morse: '··-', name: 'Uniform', icon: 'U', description: '"You are running into danger."'},
			{letter: 'V', morse: '···-', name: 'Victor', icon: 'V', description: '"I require assistance." '},
			{letter: 'W', morse: '·--', name: 'Whiskey', icon: 'W', description: '"I require medical assistance." '},
			{letter: 'X', morse: '-··-', name: 'X-ray', icon: 'X', description: '"Stop carrying out your intentions and watch for my signals." '},
			{letter: 'Y', morse: '-·--', name: 'Yankee', icon: 'Y', description: '"I am dragging my anchor." '},
			{letter: 'Z', morse: '--··', name: 'Zulu', icon: 'Z', description: '"I require a tug."By fishing vessels near fishing grounds: "I am shooting nets."'},
		]
	},
	{
		header: 'Numeric flags',
		isNavigational: true,
		flags: [
			{letter: '0', morse: '·----', name: 'Zero', icon: '0', description: 'Zero'},
			{letter: '1', morse: '··---', name: 'One', icon: '1', description: 'One'},
			{letter: '2', morse: '···--', name: 'Two', icon: '2', description: 'Two'},
			{letter: '3', morse: '····-', name: 'Three', icon: '3', description: 'Three'},
			{letter: '4', morse: '·····', name: 'Four', icon: '4', description: 'Four'},
			{letter: '5', morse: '-····', name: 'Five', icon: '5', description: 'Five'},
			{letter: '6', morse: '--···', name: 'Six', icon: '6', description: 'Six'},
			{letter: '7', morse: '---··', name: 'Seven', icon: '7', description: 'Seven'},
			{letter: '8', morse: '----·', name: 'Eight', icon: '8', description: 'Eight'},
			{letter: '9', morse: '-----', name: 'Nine', icon: '9', description: 'Nine'},				
		]
	},
	{
		header: 'National flags',
		isNavigational: false,
		flags: countries.map(country => ({name: country.name, icon: country.iso}))
		// flags: [
		// 	{name: 'Afghanistan', icon: 'AF'},
		// 	{name: 'Albania', icon: 'AL'},
		// 	{name: 'Algeria', icon: 'DZ'},
		// 	{name: 'Andorra', icon: 'AD'},
		// 	{name: 'Angola', icon: 'AO'},
		// 	{name: 'Antigua and Barbuda', icon: 'AG'},
		// 	{name: 'Argentina', icon: 'AR'},
		// 	{name: 'Armenia', icon: 'AM'},
		// 	{name: 'Australia', icon: 'AU'},
		// 	{name: 'Austria', icon: 'AT'},
		// 	{name: 'Azerbaijan', icon: 'AZ'},
		// 	{name: 'Bahamas', icon: 'BS'},
		// 	{name: 'Bahrain', icon: 'BH'},
		// 	{name: 'Bangladesh', icon: 'BD'},
		// 	{name: 'Barbados', icon: 'BB'},
		// 	{name: 'Belarus', icon: 'BY'},
		// 	{name: 'Belgium', icon: 'BE'},
		// 	{name: 'Belize', icon: 'BZ'},
		// 	{name: 'Benin', icon: 'BJ'},
		// 	{name: 'Bhutan', icon: 'BT'},
		// 	{name: 'Bolivia', icon: 'BO'},
		// 	{name: 'Bosnia and Herzegovina', icon: 'BA'},
		// 	{name: 'Botswana', icon: 'BW'},
		// 	{name: 'Brazil', icon: 'BR'},
		// 	{name: 'Brunei', icon: 'BN'},
		// 	{name: 'Bulgaria', icon: 'BG'},
		// 	{name: 'Burkina Faso', icon: 'BF'},
		// 	{name: 'Burundi', icon: 'BI'},
		// 	{name: 'Cabo Verde', icon: 'CV'},
		// 	{name: 'Cambodia', icon: 'KH'},
		// 	{name: 'Cameroon', icon: 'CM'},
		// 	{name: 'Canada', icon: 'CA'},
		// 	{name: 'Central African Republic', icon: 'CF'},
		// 	{name: 'Chad', icon: 'TD'},
		// 	{name: 'Chile', icon: 'CL'},
		// 	{name: 'China', icon: 'CN'},
		// 	{name: 'Colombia', icon: 'CO'},
		// 	{name: 'Comoros', icon: 'KM'},
		// 	{name: 'Congo (Congo-Brazzaville)', icon: 'CG'},
		// 	{name: 'Congo (DRC)', icon: 'CD'},
		// 	{name: 'Costa Rica', icon: 'CR'},
		// 	{name: 'Croatia', icon: 'HR'},
		// 	{name: 'Cuba', icon: 'CU'},
		// 	{name: 'Cyprus', icon: 'CY'},
		// 	{name: 'Czechia (Czech Republic)', icon: 'CZ'},
		// 	{name: 'Denmark', icon: 'DK'},
		// 	{name: 'Djibouti', icon: 'DJ'},
		// 	{name: 'Dominica', icon: 'DM'},
		// 	{name: 'Dominican Republic', icon: 'DO'},
		// 	{name: 'Ecuador', icon: 'EC'},
		// 	{name: 'Egypt', icon: 'EG'},
		// 	{name: 'El Salvador', icon: 'SV'},
		// 	{name: 'Equatorial Guinea', icon: 'GQ'},
		// 	{name: 'Eritrea', icon: 'ER'},
		// 	{name: 'Estonia', icon: 'EE'},
		// 	{name: 'Eswatini', icon: 'SZ'},
		// 	{name: 'Ethiopia', icon: 'ET'},
		// 	{name: 'Fiji', icon: 'FJ'},
		// 	{name: 'Finland', icon: 'FI'},
		// 	{name: 'France', icon: 'FR'},
		// 	{name: 'Gabon', icon: 'GA'},
		// 	{name: 'Gambia', icon: 'GM'},
		// 	{name: 'Georgia', icon: 'GE'},
		// 	{name: 'Germany', icon: 'DE'},
		// 	{name: 'Ghana', icon: 'GH'},
		// 	{name: 'Greece', icon: 'GR'},
		// 	{name: 'Grenada', icon: 'GD'},
		// 	{name: 'Guatemala', icon: 'GT'},
		// 	{name: 'Guinea', icon: 'GN'},
		// 	{name: 'Guinea-Bissau', icon: 'GW'},
		// 	{name: 'Guyana', icon: 'GY'},
		// 	{name: 'Haiti', icon: 'HT'},
		// 	{name: 'Holy See', icon: 'VA'},
		// 	{name: 'Honduras', icon: 'HN'},
		// 	{name: 'Hungary', icon: 'HU'},
		// 	{name: 'Iceland', icon: 'IS'},
		// 	{name: 'India', icon: 'IN'},
		// 	{name: 'Indonesia', icon: 'ID'},
		// 	{name: 'Iran', icon: 'IR'},
		// 	{name: 'Iraq', icon: 'IQ'},
		// 	{name: 'Ireland', icon: 'IE'},
		// 	{name: 'Israel', icon: 'IL'},
		// 	{name: 'Italy', icon: 'IT'},
		// 	{name: 'Jamaica', icon: 'JM'},
		// 	{name: 'Japan', icon: 'JP'},
		// 	{name: 'Jordan', icon: 'JO'},
		// 	{name: 'Kazakhstan', icon: 'KZ'},
		// 	{name: 'Kenya', icon: 'KE'},
		// 	{name: 'Kiribati', icon: 'KI'},
		// 	{name: 'Korea (North)', icon: 'KP'},
		// 	{name: 'Korea (South)', icon: 'KR'},
		// 	{name: 'Kosovo', icon: 'XK'},
		// 	{name: 'Kuwait', icon: 'KW'},
		// 	{name: 'Kyrgyzstan', icon: 'KG'},
		// 	{name: 'Laos', icon: 'LA'},
		// 	{name: 'Latvia', icon: 'LV'},
		// 	{name: 'Lebanon', icon: 'LB'},
		// 	{name: 'Lesotho', icon: 'LS'},
		// 	{name: 'Liberia', icon: 'LR'},
		// 	{name: 'Libya', icon: 'LY'},
		// 	{name: 'Liechtenstein', icon: 'LI'},
		// 	{name: 'Lithuania', icon: 'LT'},
		// 	{name: 'Luxembourg', icon: 'LU'},
		// 	{name: 'Madagascar', icon: 'MG'},
		// 	{name: 'Malawi', icon: 'MW'},
		// 	{name: 'Malaysia', icon: 'MY'},
		// 	{name: 'Maldives', icon: 'MV'},
		// 	{name: 'Mali', icon: 'ML'},
		// 	{name: 'Malta', icon: 'MT'},
		// 	{name: 'Marshall Islands', icon: 'MH'},
		// 	{name: 'Mauritania', icon: 'MR'},
		// 	{name: 'Mauritius', icon: 'MU'},
		// 	{name: 'Mexico', icon: 'MX'},
		// 	{name: 'Micronesia', icon: 'FM'},
		// 	{name: 'Moldova', icon: 'MD'},
		// 	{name: 'Monaco', icon: 'MC'},
		// 	{name: 'Mongolia', icon: 'MN'},
		// 	{name: 'Montenegro', icon: 'ME'},
		// 	{name: 'Morocco', icon: 'MA'},
		// 	{name: 'Mozambique', icon: 'MZ'},
		// 	{name: 'Myanmar (Burma)', icon: 'MM'},
		// 	{name: 'Namibia', icon: 'NA'},
		// 	{name: 'Nauru', icon: 'NR'},
		// 	{name: 'Nepal', icon: 'NP'},
		// 	{name: 'Netherlands', icon: 'NL'},
		// 	{name: 'New Zealand', icon: 'NZ'},
		// 	{name: 'Nicaragua', icon: 'NI'},
		// 	{name: 'Niger', icon: 'NE'},
		// 	{name: 'Nigeria', icon: 'NG'},
		// 	{name: 'North Macedonia', icon: 'MK'},
		// 	{name: 'Norway', icon: 'NO'},
		// 	{name: 'Oman', icon: 'OM'},
		// 	{name: 'Pakistan', icon: 'PK'},
		// 	{name: 'Palau', icon: 'PW'},
		// 	{name: 'Palestine State', icon: 'PS'},
		// 	{name: 'Panama', icon: 'PA'},
		// 	{name: 'Papua New Guinea', icon: 'PG'},
		// 	{name: 'Paraguay', icon: 'PY'},
		// 	{name: 'Peru', icon: 'PE'},
		// 	{name: 'Philippines', icon: 'PH'},
		// 	{name: 'Poland', icon: 'PL'},
		// 	{name: 'Portugal', icon: 'PT'},
		// 	{name: 'Qatar', icon: 'QA'},
		// 	{name: 'Romania', icon: 'RO'},
		// 	{name: 'Russia', icon: 'RU'},
		// 	{name: 'Rwanda', icon: 'RW'},
		// 	{name: 'Saint Kitts and Nevis', icon: 'KN'},
		// 	{name: 'Saint Lucia', icon: 'LC'},
		// 	{name: 'Saint Vincent and the Grenadines', icon: 'VC'},
		// 	{name: 'Samoa', icon: 'WS'},
		// 	{name: 'San Marino', icon: 'SM'},
		// 	{name: 'Sao Tome and Principe', icon: 'ST'},
		// 	{name: 'Saudi Arabia', icon: 'SA'},
		// 	{name: 'Senegal', icon: 'SN'},
		// 	{name: 'Serbia', icon: 'RS'},
		// 	{name: 'Seychelles', icon: 'SC'},
		// 	{name: 'Sierra Leone', icon: 'SL'},
		// 	{name: 'Singapore', icon: 'SG'},
		// 	{name: 'Slovakia', icon: 'SK'},
		// 	{name: 'Slovenia', icon: 'SI'},
		// 	{name: 'Solomon Islands', icon: 'SB'},
		// 	{name: 'Somalia', icon: 'SO'},
		// 	{name: 'South Africa', icon: 'ZA'},
		// 	{name: 'South Sudan', icon: 'SS'},
		// 	{name: 'Spain', icon: 'ES'},
		// 	{name: 'Sri Lanka', icon: 'LK'},
		// 	{name: 'Sudan', icon: 'SD'},
		// 	{name: 'Suriname', icon: 'SR'},
		// 	{name: 'Sweden', icon: 'SE'},
		// 	{name: 'Switzerland', icon: 'CH'},
		// 	{name: 'Syria', icon: 'SY'},
		// 	{name: 'Tajikistan', icon: 'TJ'},
		// 	{name: 'Tanzania', icon: 'TZ'},
		// 	{name: 'Thailand', icon: 'TH'},
		// 	{name: 'Timor-Leste', icon: 'TL'},
		// 	{name: 'Togo', icon: 'TG'},
		// 	{name: 'Tonga', icon: 'TO'},
		// 	{name: 'Trinidad and Tobago', icon: 'TT'},
		// 	{name: 'Tunisia', icon: 'TN'},
		// 	{name: 'Turkey', icon: 'TR'},
		// 	{name: 'Turkmenistan', icon: 'TM'},
		// 	{name: 'Tuvalu', icon: 'TV'},
		// 	{name: 'Uganda', icon: 'UG'},
		// 	{name: 'Ukraine', icon: 'UA'},
		// 	{name: 'United Arab Emirates', icon: 'AE'},
		// 	{name: 'United Kingdom', icon: 'GB'},
		// 	{name: 'United States', icon: 'US'},
		// 	{name: 'Uruguay', icon: 'UY'},
		// 	{name: 'Uzbekistan', icon: 'UZ'},
		// 	{name: 'Vanuatu', icon: 'VU'},
		// 	{name: 'Venezuela', icon: 'VE'},
		// 	{name: 'Vietnam', icon: 'VN'},
		// 	{name: 'Yemen', icon: 'YE'},
		// 	{name: 'Zambia', icon: 'ZM'},
		// 	{name: 'Zimbabwe', icon: 'ZW'}
		// ]
	}
]

